title : Paul Shannon
production_url : http://paulshannon.ca
description: "Things by Paul Shannon."

author :
  name : Paul Shannon
  github : paulshannon
  twitter : paulshannon
  email: paul@paulshannon.ca

disqus_shortname: paulshannon
analytics: UA-196062-4

permalink: /:categories/:year/:month/:day/:title
highlighter: pygments
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]
exclude: [ Gemfile, Gemfile.lock, gems, _assets, bower_components ]